SELECT
SUM(CASE WHEN replacement_cost BETWEEN 9.99 AND 19.99 THEN 1 END) AS "LOW COST",
SUM(CASE WHEN replacement_cost BETWEEN 20.00 AND 24.99 THEN 1 END) AS "MEDIUM COST",
SUM(CASE WHEN replacement_cost BETWEEN 25 AND 29.99 THEN 1 END) AS "HIGH COST"
FROM film 